apiVersion: v1
kind: Service
metadata:
  name: state-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: state
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080  # Optional: Specify a port between 30000-32767; if omitted, Kubernetes assigns one
    protocol: TCP
    name: state
