apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-multi-deployment
  namespace: default
  labels:
    app: multi-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-dep
  template:
    metadata:
      labels:
        app: multi-dep
    spec:
      containers:
      - name: main
        image: localhost:32000/test2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: sidecar
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
