apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: my-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
